# -*- coding: utf-8 -*-
"""Predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GGBt8N2Cz8MXdmwCC0z9bi1KDbMYrql
"""

import os
import argparse
import librosa
import numpy as np
import tensorflow as tf

# Suppress TensorFlow logging for a cleaner terminal output
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# --- CONFIGURATION ---
MODEL_PATH = 'final_deepfake_audio_detector.keras'
SAMPLE_RATE = 16000
DURATION = 3
N_MELS = 128

def extract_and_preprocess(file_path):
    try:
        # Load audio file
        audio, sr = librosa.load(file_path, sr=SAMPLE_RATE)
        
        # FIX 1: Strip leading and trailing silence (helps with real-world mic recordings)
        audio, _ = librosa.effects.trim(audio, top_db=20)
        
        target_length = SAMPLE_RATE * DURATION
        
        # Pad or truncate audio to ensure uniform length
        if len(audio) < target_length:
            pad_length = target_length - len(audio)
            # FIX 2: Use 'wrap' instead of 'constant' zeros. 
            # If the audio is too short, it loops the voice instead of adding unnatural digital silence.
            audio = np.pad(audio, (0, pad_length), mode='wrap')
        else:
            audio = audio[:target_length]
            
        # Extract Log-Mel Spectrogram
        mel_spec = librosa.feature.melspectrogram(y=audio, sr=SAMPLE_RATE, n_mels=N_MELS, fmax=8000)
        log_mel_spec = librosa.power_to_db(mel_spec, ref=np.max)
        
        # Transpose so Time is the first dimension
        features = log_mel_spec.T 
        
        # Normalize (Instance Normalization)
        mean = np.mean(features)
        std = np.std(features)
        features = (features - mean) / (std + 1e-8)
        
        # Reshape for 2D CNN: (Batch, Time, Mels, Channel)
        # Adding the channel dimension for grayscale image format
        features = features[np.newaxis, ..., np.newaxis] 
        return features.astype(np.float32)
        
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None

def predict_audio(file_path):
    """Loads the model and predicts if the audio is Genuine or Deepfake."""
    if not os.path.exists(file_path):
        print(f"Error: The file '{file_path}' does not exist.")
        return

    if not os.path.exists(MODEL_PATH):
        print(f"Error: Model file '{MODEL_PATH}' not found. Ensure it is in the same directory.")
        return

    print(f"Analyzing audio: {file_path}...")

    # Load Model
    model = tf.keras.models.load_model(MODEL_PATH)

    # Process Audio
    features = extract_and_preprocess(file_path)

    if features is not None:
        # Predict
        prediction_prob = model.predict(features, verbose=0)[0][0]

        # Output Results
        print("-" * 30)
        if prediction_prob > 0.5:
            confidence = prediction_prob * 100
            print(f"🚨 VERDICT: DEEPFAKE (AI-Generated)")
            print(f"Confidence: {confidence:.2f}%")
        else:
            confidence = (1 - prediction_prob) * 100
            print(f"✅ VERDICT: GENUINE (Human)")
            print(f"Confidence: {confidence:.2f}%")
        print("-" * 30)

if __name__ == "__main__":
    # Setup command line argument parsing
    parser = argparse.ArgumentParser(description="Deepfake Audio Detection Inference Script")
    parser.add_argument("audio_file", type=str, help="Path to the .wav or .flac audio file to test")

    args = parser.parse_args()
    predict_audio(args.audio_file)
